30, 8
"action0", "target0", 0, 0, 30, 1, "0000n.bin", "0000s.bin"
"action1", "target1", 0, 1, 30, 1, "0001n.bin", "0001s.bin"
"action2", "target2", 0, 2, 30, 1, "0002n.bin", "0002s.bin"
"action3", "target3", 0, 3, 30, 1, "0003n.bin", "0003s.bin"
"action4", "target4", 0, 4, 30, 1, "0004n.bin", "0004s.bin"
"action5", "target5", 0, 5, 30, 1, "0005n.bin", "0005s.bin"
"action6", "target6", 0, 6, 30, 1, "0006n.bin", "0006s.bin"
"action7", "target7", 0, 7, 30, 1, "0007n.bin", "0007s.bin"
